/*
 * Podman Desktop AI Lab API
 *
 * API for interacting with the Podman Desktop AI Lab service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListResponse : Response from a list request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponse {
    #[serde(rename = "models", skip_serializing_if = "Option::is_none")]
    pub models: Option<Vec<models::ListModelResponse>>,
}

impl ListResponse {
    /// Response from a list request
    pub fn new() -> ListResponse {
        ListResponse {
            models: None,
        }
    }
}

